services:
  # Base de données MongoDB
  db:
    image: mongo:7
    container_name: adtech-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: adtech
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ hello: 1 })' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: adtech-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend NestJS
  backend:
    build:
      context: ./backend
      target: development
    container_name: adtech-backend
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://admin:admin123@db:27017/adtech?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: adtech-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000 
      - WATCHPACK_POLLING=true
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next 

volumes:
  mongo_data:
  redis_data: